import type { Mission, MissionTurn } from "./learning-content.ts";

type Reply = [line: string, translation: string, task: string, answer: string];
type Chapter = {
  id: string;
  topic: string;
  title: string;
  place: string;
  challenge: string;
  listen: [line: string, translation: string, task: string, answer: string, alternative: string, other: string];
  build: Reply;
  reply: Reply;
  finish: Reply;
};

function response(kind: "build" | "respond", entry: Reply): MissionTurn {
  const [line, translation, task, answer] = entry;
  return {
    kind, line, translation, task, accepted: [answer],
    ...(kind === "build" ? { words: answer.split(" ").reverse() } : {}),
    note: `${answer} = ${task}. Other wording may also be valid; this exercise checks the model phrase.`,
  };
}

const chapters: Chapter[] = [
  {
    id: "supermarket", topic: "Shopping", title: "Find the right aisle", place: "At the supermarket",
    challenge: "Ask a member of staff where an everyday ingredient is.",
    listen: ["Die Nudeln stehen in Gang vier, neben dem Reis.", "The pasta is in aisle four, next to the rice.", "Where is the pasta?", "Aisle four, beside the rice", "Aisle two, beside the bread", "At the checkout"],
    build: ["Suchen Sie noch etwas?", "Are you looking for anything else?", "Where can I find the milk?", "Wo finde ich die Milch"],
    reply: ["Die Milch steht hinten im Kühlregal.", "The milk is at the back in the refrigerated section.", "Do you also have oat milk?", "Haben Sie auch Hafermilch"],
    finish: ["Ja, direkt daneben.", "Yes, right next to it.", "Thank you for your help", "Danke für Ihre Hilfe"],
  },
  {
    id: "market", topic: "Food", title: "Fresh from the market", place: "At the market",
    challenge: "Ask the price of fruit and buy a specific quantity.",
    listen: ["Die Äpfel kosten drei Euro pro Kilo. Die Birnen kosten vier Euro.", "The apples cost three euros per kilo. The pears cost four euros.", "How much is a kilo of apples?", "Three euros", "Four euros", "Seven euros"],
    build: ["Was darf es sein?", "What would you like?", "I would like a kilo of apples", "Ich hätte gern ein Kilo Äpfel"],
    reply: ["Möchten Sie auch Birnen?", "Would you like pears too?", "Can I try one?", "Kann ich eine probieren"],
    finish: ["Natürlich, hier bitte.", "Of course, here you are.", "They taste good", "Die schmecken gut"],
  },
  {
    id: "vegetarian", topic: "Food", title: "A meat-free lunch", place: "At the canteen",
    challenge: "Ask about a vegetarian option and a substitution.",
    listen: ["Heute gibt es Gemüsecurry mit Reis. Die Suppe enthält Hühnerbrühe.", "Today there is vegetable curry with rice. The soup contains chicken stock.", "Which dish contains chicken stock?", "The soup", "The curry", "The rice"],
    build: ["Was möchten Sie essen?", "What would you like to eat?", "I will take the vegetable curry", "Ich nehme das Gemüsecurry"],
    reply: ["Mit Reis oder Brot?", "With rice or bread?", "With rice, please", "Mit Reis, bitte"],
    finish: ["Möchten Sie Joghurt dazu?", "Would you like yogurt with it?", "Without yogurt, please", "Ohne Joghurt, bitte"],
  },
  {
    id: "allergy", topic: "Food", title: "Check the ingredients", place: "At a food stall",
    challenge: "Practise stating an allergy and asking staff to check ingredients.",
    listen: ["Die Soße enthält Erdnüsse. Ich frage in der Küche nach einer Alternative.", "The sauce contains peanuts. I will ask the kitchen for an alternative.", "What contains peanuts?", "The sauce", "The water", "The bread"],
    build: ["Haben Sie eine Allergie?", "Do you have an allergy?", "I am allergic to peanuts", "Ich bin gegen Erdnüsse allergisch"],
    reply: ["Ich muss die Zutaten prüfen.", "I need to check the ingredients.", "Could you please ask in the kitchen?", "Könnten Sie bitte in der Küche nachfragen"],
    finish: ["Wir können Spuren leider nicht ausschließen.", "Unfortunately, we cannot rule out traces.", "Then I will not order anything", "Dann bestelle ich nichts"],
  },
  {
    id: "bill", topic: "Food", title: "Split the bill", place: "After dinner",
    challenge: "Ask to pay separately and check an item on a bill.",
    listen: ["Zusammen sind das zweiunddreißig Euro. Kartenzahlung ist möglich.", "Together that is thirty-two euros. Card payment is possible.", "What is the total?", "32 euros", "23 euros", "30 euros"],
    build: ["Zusammen oder getrennt?", "Together or separately?", "We would like to pay separately", "Wir möchten getrennt bezahlen"],
    reply: ["Was hatten Sie?", "What did you have?", "I had the soup and a water", "Ich hatte die Suppe und ein Wasser"],
    finish: ["Hier ist Ihre Rechnung.", "Here is your bill.", "Could I have the receipt, please?", "Könnte ich bitte den Beleg haben"],
  },
  {
    id: "clothes", topic: "Shopping", title: "Find your size", place: "In a clothing shop",
    challenge: "Ask for another size and find the fitting room.",
    listen: ["Die Jacke gibt es in Blau und Schwarz, aber nicht mehr in Grün.", "The jacket is available in blue and black, but no longer in green.", "Which colour is unavailable?", "Green", "Blue", "Black"],
    build: ["Welche Größe brauchen Sie?", "What size do you need?", "Do you have this in medium?", "Haben Sie das in Größe M"],
    reply: ["Ja, hier ist die blaue Jacke.", "Yes, here is the blue jacket.", "May I try it on?", "Darf ich sie anprobieren"],
    finish: ["Natürlich. Die Umkleiden sind links.", "Of course. The fitting rooms are on the left.", "It fits well", "Sie passt gut"],
  },
  {
    id: "shoes", topic: "Shopping", title: "A better fit", place: "In a shoe shop",
    challenge: "Explain a fit problem and request a different size.",
    listen: ["Dieses Modell fällt klein aus. Probieren Sie eine Nummer größer.", "This model runs small. Try one size larger.", "What does the assistant suggest?", "One size larger", "One size smaller", "A different colour"],
    build: ["Wie sitzen die Schuhe?", "How do the shoes fit?", "They are too tight", "Sie sind zu eng"],
    reply: ["Welche Größe haben Sie normalerweise?", "What size do you normally wear?", "I normally wear size forty", "Ich trage normalerweise Größe vierzig"],
    finish: ["Hier ist Größe einundvierzig.", "Here is size forty-one.", "These fit better", "Diese passen besser"],
  },
  {
    id: "return", topic: "Shopping", title: "Return a purchase", place: "At customer service",
    challenge: "Explain a faulty purchase and ask about a refund.",
    listen: ["Für die Rückgabe brauchen wir den Kassenbon und die Ware.", "For the return we need the receipt and the item.", "What must you bring?", "The receipt and item", "Only the packaging", "Your passport"],
    build: ["Was ist das Problem?", "What is the problem?", "The kettle does not work", "Der Wasserkocher funktioniert nicht"],
    reply: ["Wann haben Sie ihn gekauft?", "When did you buy it?", "I bought it yesterday", "Ich habe ihn gestern gekauft"],
    finish: ["Möchten Sie einen Ersatz?", "Would you like a replacement?", "I would like my money back", "Ich möchte mein Geld zurück"],
  },
  {
    id: "electronics", topic: "Shopping", title: "Choose a charger", place: "In an electronics shop",
    challenge: "Describe the accessory you need and check compatibility.",
    listen: ["Das Kabel kostet zehn Euro. Das Netzteil müssen Sie separat kaufen.", "The cable costs ten euros. You must buy the power adapter separately.", "What is not included?", "The power adapter", "The cable", "The receipt"],
    build: ["Was suchen Sie?", "What are you looking for?", "I need a charging cable", "Ich brauche ein Ladekabel"],
    reply: ["Für welches Gerät?", "For which device?", "For my phone", "Für mein Handy"],
    finish: ["Dieses Kabel könnte passen.", "This cable might fit.", "Can we test it?", "Können wir es testen"],
  },
  {
    id: "pharmacy", topic: "Health", title: "At the pharmacy", place: "At the pharmacy counter",
    challenge: "Practise asking a pharmacist about a prescription and instructions.",
    listen: ["Das Medikament ist nicht vorrätig. Sie können es morgen ab zehn Uhr abholen.", "The medicine is not in stock. You can collect it tomorrow from ten.", "When can you collect it?", "Tomorrow from 10", "Today from 10", "Tomorrow before 8"],
    build: ["Haben Sie ein Rezept?", "Do you have a prescription?", "Yes, here is my prescription", "Ja, hier ist mein Rezept"],
    reply: ["Ich bestelle das Medikament für Sie.", "I will order the medicine for you.", "How should I take it?", "Wie soll ich es einnehmen"],
    finish: ["Das erkläre ich Ihnen bei der Abholung.", "I will explain that when you collect it.", "Could you write that down?", "Könnten Sie das aufschreiben"],
  },
  {
    id: "doctor", topic: "Health", title: "Describe how you feel", place: "In the consulting room",
    challenge: "Rehearse describing symptoms and how long you have had them.",
    listen: ["Bitte nehmen Sie im Wartezimmer Platz. Die Ärztin ruft Sie auf.", "Please take a seat in the waiting room. The doctor will call you.", "What should you do now?", "Sit in the waiting room", "Go home", "Call the doctor"],
    build: ["Was fehlt Ihnen?", "What is wrong?", "I have a headache", "Ich habe Kopfschmerzen"],
    reply: ["Seit wann haben Sie die Beschwerden?", "How long have you had the symptoms?", "Since yesterday evening", "Seit gestern Abend"],
    finish: ["Nehmen Sie regelmäßig Medikamente?", "Do you take medication regularly?", "No, I do not take any medication", "Nein, ich nehme keine Medikamente"],
  },
  {
    id: "dentist", topic: "Health", title: "A dental appointment", place: "At the dentist",
    challenge: "Explain where something hurts and ask for a slower explanation.",
    listen: ["Wir haben heute um vierzehn Uhr einen Termin frei, morgen leider nicht.", "We have an appointment available today at fourteen, unfortunately not tomorrow.", "When is an appointment available?", "Today at 14:00", "Tomorrow at 14:00", "Today at 16:00"],
    build: ["Wo haben Sie Schmerzen?", "Where do you have pain?", "This tooth hurts", "Dieser Zahn tut weh"],
    reply: ["Können Sie heute kommen?", "Can you come today?", "Yes, I can come at two", "Ja, ich kann um zwei kommen"],
    finish: ["Ich erkläre Ihnen den Ablauf.", "I will explain the procedure.", "Could you speak more slowly?", "Könnten Sie langsamer sprechen"],
  },
  {
    id: "optician", topic: "Health", title: "Repair your glasses", place: "At the optician",
    challenge: "Explain a problem with glasses and ask about repair time.",
    listen: ["Die Reparatur dauert ungefähr zwanzig Minuten und kostet fünf Euro.", "The repair takes about twenty minutes and costs five euros.", "How long will it take?", "About twenty minutes", "About five minutes", "Two days"],
    build: ["Was ist mit Ihrer Brille passiert?", "What happened to your glasses?", "My glasses are broken", "Meine Brille ist kaputt"],
    reply: ["Wir können den Bügel reparieren.", "We can repair the arm.", "Can I wait here?", "Kann ich hier warten"],
    finish: ["Ja, nehmen Sie bitte Platz.", "Yes, please take a seat.", "Thank you, that is very kind", "Danke, das ist sehr nett"],
  },
  {
    id: "urgent-help", topic: "Health", title: "Ask for urgent help", place: "Asking for help",
    challenge: "Rehearse giving a location and asking someone to call for help. This is language practice, not medical guidance.",
    listen: ["Bleiben Sie bitte am Telefon und nennen Sie mir Ihre Adresse.", "Please stay on the phone and tell me your address.", "What information is requested?", "Your address", "Your bank number", "Your appointment date"],
    build: ["Was brauchen Sie?", "What do you need?", "Please call an ambulance", "Bitte rufen Sie einen Krankenwagen"],
    reply: ["Wo sind Sie?", "Where are you?", "I am at the station", "Ich bin am Bahnhof"],
    finish: ["Sind Sie allein?", "Are you alone?", "No, someone is with me", "Nein, jemand ist bei mir"],
  },
  {
    id: "apartment", topic: "Home", title: "Ask about a room", place: "Looking for a shared flat",
    challenge: "Write or rehearse a short enquiry about a room.",
    listen: ["Das Zimmer ist ab Oktober frei. Die Warmmiete beträgt fünfhundert Euro.", "The room is available from October. The rent including running costs is five hundred euros.", "When is the room available?", "From October", "From August", "From December"],
    build: ["Interessieren Sie sich für das Zimmer?", "Are you interested in the room?", "Yes, is the room still available?", "Ja, ist das Zimmer noch frei"],
    reply: ["Ja, möchten Sie es besichtigen?", "Yes, would you like to view it?", "When can I view the room?", "Wann kann ich das Zimmer besichtigen"],
    finish: ["Am Samstag um elf Uhr.", "On Saturday at eleven.", "Saturday works well for me", "Samstag passt mir gut"],
  },
  {
    id: "viewing", topic: "Home", title: "View an apartment", place: "At an apartment viewing",
    challenge: "Ask about included costs and the deposit.",
    listen: ["Heizung und Wasser sind enthalten. Strom zahlen Sie extra.", "Heating and water are included. You pay electricity separately.", "Which cost is separate?", "Electricity", "Heating", "Water"],
    build: ["Haben Sie Fragen zur Wohnung?", "Do you have questions about the apartment?", "How much is the deposit?", "Wie hoch ist die Kaution"],
    reply: ["Die Kaution beträgt zwei Monatsmieten.", "The deposit is two months of rent.", "Is the kitchen included?", "Ist die Küche dabei"],
    finish: ["Ja, die Küche bleibt in der Wohnung.", "Yes, the kitchen stays in the apartment.", "When could I move in?", "Wann könnte ich einziehen"],
  },
  {
    id: "heating", topic: "Home", title: "Report a repair", place: "Calling the landlord",
    challenge: "Describe a household fault and arrange access for a repair.",
    listen: ["Der Techniker kommt morgen zwischen acht und zehn Uhr.", "The technician comes tomorrow between eight and ten.", "When will the technician arrive?", "Tomorrow between 8 and 10", "Today at 10", "Tomorrow after 18"],
    build: ["Was funktioniert nicht?", "What is not working?", "The heating does not work", "Die Heizung funktioniert nicht"],
    reply: ["Seit wann ist das so?", "Since when has it been like that?", "Since Monday", "Seit Montag"],
    finish: ["Sind Sie morgen zu Hause?", "Are you at home tomorrow?", "I am at home until ten", "Ich bin bis zehn zu Hause"],
  },
  {
    id: "laundry", topic: "Home", title: "Use the laundry room", place: "In the laundry room",
    challenge: "Ask how a shared facility works and clarify a house rule.",
    listen: ["Die Waschmaschine kostet zwei Euro. Nach zweiundzwanzig Uhr ist Waschen nicht erlaubt.", "The washing machine costs two euros. Washing is not allowed after twenty-two hundred.", "When is washing not allowed?", "After 22:00", "Before 12:00", "All Saturday"],
    build: ["Benutzen Sie die Maschine zum ersten Mal?", "Are you using the machine for the first time?", "How does the machine work?", "Wie funktioniert die Maschine"],
    reply: ["Sie brauchen zwei Münzen.", "You need two coins.", "Where can I change money?", "Wo kann ich Geld wechseln"],
    finish: ["Fragen Sie bitte an der Rezeption.", "Please ask at reception.", "Thank you, I will do that", "Danke, das mache ich"],
  },
  {
    id: "recycling", topic: "Home", title: "Sort the rubbish", place: "By the bins",
    challenge: "Ask which bin to use instead of guessing local recycling rules.",
    listen: ["Papier kommt hier in die blaue Tonne. Glas bringen wir zum Container an der Ecke.", "Paper goes in the blue bin here. We take glass to the container on the corner.", "Where does glass go?", "To the container on the corner", "In the blue bin", "In the laundry room"],
    build: ["Was möchten Sie wegwerfen?", "What would you like to throw away?", "Where does this belong?", "Wo gehört das hin"],
    reply: ["Ist das Papier oder Plastik?", "Is that paper or plastic?", "It is plastic", "Das ist Plastik"],
    finish: ["Dann nehmen Sie bitte die gelbe Tonne.", "Then please use the yellow bin.", "Thanks for explaining", "Danke für die Erklärung"],
  },
  {
    id: "parcel", topic: "Home", title: "Collect your parcel", place: "At a neighbor's door",
    challenge: "Ask a neighbor about a delivery and confirm your name.",
    listen: ["Ihr Paket liegt bei Frau Müller im zweiten Stock.", "Your parcel is with Ms Müller on the second floor.", "Where is the parcel?", "With Ms Müller on the second floor", "At the post office", "In the basement"],
    build: ["Guten Abend, was gibt es?", "Good evening, what is it?", "Did you accept a parcel for me?", "Haben Sie ein Paket für mich angenommen"],
    reply: ["Auf welchen Namen?", "Under what name?", "My name is Alex Weber", "Ich heiße Alex Weber"],
    finish: ["Ja, hier ist Ihr Paket.", "Yes, here is your parcel.", "Thank you for accepting it", "Danke fürs Annehmen"],
  },
  {
    id: "internet", topic: "Home", title: "Fix the connection", place: "Calling internet support",
    challenge: "Describe a connection issue and request a written confirmation.",
    listen: ["In Ihrer Straße gibt es eine Störung. Wir arbeiten bis sechzehn Uhr daran.", "There is an outage in your street. We are working on it until sixteen hundred.", "What is the problem?", "An outage in the street", "An unpaid bill", "A lost password"],
    build: ["Wie können wir helfen?", "How can we help?", "My internet is not working", "Mein Internet funktioniert nicht"],
    reply: ["Haben Sie den Router neu gestartet?", "Have you restarted the router?", "Yes, but it has not helped", "Ja, aber es hat nicht geholfen"],
    finish: ["Wir melden uns, sobald die Störung behoben ist.", "We will contact you as soon as the outage is fixed.", "Please send me an email", "Bitte schicken Sie mir eine E-Mail"],
  },
  {
    id: "rent", topic: "Home", title: "Clarify the rent", place: "Discussing rent",
    challenge: "Ask for clarification about a payment and confirm a transfer.",
    listen: ["Bitte überweisen Sie die Miete bis zum dritten Werktag des Monats.", "Please transfer the rent by the third working day of the month.", "What deadline is stated?", "The third working day", "The last Sunday", "The fifteenth day"],
    build: ["Haben Sie die Bankverbindung?", "Do you have the bank details?", "Could you send me the bank details?", "Könnten Sie mir die Bankverbindung schicken"],
    reply: ["Ich schicke sie Ihnen heute.", "I will send them to you today.", "I will transfer the rent tomorrow", "Ich überweise die Miete morgen"],
    finish: ["Bitte geben Sie Ihre Wohnungsnummer an.", "Please include your apartment number.", "Where should I enter it?", "Wo soll ich sie eintragen"],
  },
  {
    id: "bank", topic: "Services", title: "Open an account", place: "At the bank",
    challenge: "Ask which documents and fees apply to an account.",
    listen: ["Bitte bringen Sie Ihren Ausweis und eine Meldebescheinigung mit.", "Please bring your ID and a registration certificate.", "Which documents are requested?", "ID and registration certificate", "A train ticket and receipt", "Only a student card"],
    build: ["Was möchten Sie erledigen?", "What would you like to do?", "I would like to open an account", "Ich möchte ein Konto eröffnen"],
    reply: ["Wir bieten verschiedene Konten an.", "We offer various accounts.", "Are there monthly fees?", "Gibt es monatliche Gebühren"],
    finish: ["Für Studierende gibt es ein besonderes Angebot.", "There is a special offer for students.", "Could you explain the conditions?", "Könnten Sie die Bedingungen erklären"],
  },
  {
    id: "registration", topic: "Services", title: "Register your address", place: "At the citizens' office",
    challenge: "Rehearse an address-registration appointment; verify local document requirements separately.",
    listen: ["Ihre Wartenummer ist zweiundvierzig. Gehen Sie bitte zu Schalter drei.", "Your waiting number is forty-two. Please go to counter three.", "Which counter should you use?", "Counter three", "Counter forty-two", "Counter two"],
    build: ["Was ist Ihr Anliegen?", "What is your request?", "I would like to register my address", "Ich möchte meinen Wohnsitz anmelden"],
    reply: ["Haben Sie die Wohnungsgeberbestätigung dabei?", "Do you have the landlord's confirmation with you?", "Yes, here are my documents", "Ja, hier sind meine Unterlagen"],
    finish: ["Bitte unterschreiben Sie hier.", "Please sign here.", "Could I have a copy?", "Könnte ich eine Kopie haben"],
  },
  {
    id: "residence", topic: "Services", title: "Check an application", place: "At the immigration office",
    challenge: "Ask about missing documents and a deadline; this is language practice, not immigration advice.",
    listen: ["Es fehlt noch ein Foto. Bitte reichen Sie es bis Freitag nach.", "A photo is still missing. Please submit it by Friday.", "What is missing?", "A photo", "A signature", "A bank card"],
    build: ["Haben Sie Fragen zu Ihrem Antrag?", "Do you have questions about your application?", "Which documents are still missing?", "Welche Unterlagen fehlen noch"],
    reply: ["Wir brauchen das Foto bis Freitag.", "We need the photo by Friday.", "Can I submit it online?", "Kann ich es online einreichen"],
    finish: ["Ja, nutzen Sie bitte unser Portal.", "Yes, please use our portal.", "Could you send me the link?", "Könnten Sie mir den Link schicken"],
  },
  {
    id: "insurance", topic: "Services", title: "Request a certificate", place: "Calling your insurer",
    challenge: "Ask for an insurance certificate and confirm how it will arrive.",
    listen: ["Wir schicken die Bescheinigung per Post. Sie kommt in drei Werktagen an.", "We will send the certificate by post. It will arrive in three working days.", "How will the certificate arrive?", "By post", "By text message", "Only in person"],
    build: ["Was benötigen Sie?", "What do you need?", "I need an insurance certificate", "Ich brauche eine Versicherungsbescheinigung"],
    reply: ["Wofür brauchen Sie die Bescheinigung?", "What do you need the certificate for?", "For my university", "Für meine Universität"],
    finish: ["Ist Ihre Adresse noch aktuell?", "Is your address still current?", "Yes, the address is correct", "Ja, die Adresse stimmt"],
  },
  {
    id: "post", topic: "Services", title: "Send a parcel", place: "At the post office",
    challenge: "Ask about parcel delivery and tracking.",
    listen: ["Das Paket braucht zwei bis drei Werktage. Die Sendungsverfolgung ist dabei.", "The parcel takes two to three working days. Tracking is included.", "What is included?", "Tracking", "Same-day delivery", "Gift wrapping"],
    build: ["Wohin geht das Paket?", "Where is the parcel going?", "I would like to send this to Berlin", "Ich möchte das nach Berlin schicken"],
    reply: ["Möchten Sie einen Einlieferungsbeleg?", "Would you like a proof-of-posting receipt?", "Yes, please give me the receipt", "Ja, bitte geben Sie mir den Beleg"],
    finish: ["Hier steht die Sendungsnummer.", "The tracking number is written here.", "Where can I track the parcel?", "Wo kann ich das Paket verfolgen"],
  },
  {
    id: "library", topic: "Study", title: "Borrow a book", place: "At the library",
    challenge: "Ask to borrow a book and check the return date.",
    listen: ["Sie können das Buch vier Wochen ausleihen. Eine Verlängerung ist online möglich.", "You can borrow the book for four weeks. Renewal is possible online.", "How long is the loan?", "Four weeks", "Four days", "Two weeks"],
    build: ["Haben Sie einen Bibliotheksausweis?", "Do you have a library card?", "I would like to apply for a library card", "Ich möchte einen Bibliotheksausweis beantragen"],
    reply: ["Bitte zeigen Sie Ihren Ausweis.", "Please show your ID.", "Here is my ID", "Hier ist mein Ausweis"],
    finish: ["Jetzt können Sie das Buch ausleihen.", "Now you can borrow the book.", "When must I return it?", "Wann muss ich es zurückgeben"],
  },
  {
    id: "seminar", topic: "Study", title: "Find your seminar", place: "On campus",
    challenge: "Ask about a room change and when a class starts.",
    listen: ["Das Seminar findet heute in Raum zweihundertzehn statt, nicht in Raum hundertzwanzig.", "The seminar is in room two hundred ten today, not room one hundred twenty.", "Which room is correct?", "Room 210", "Room 120", "Room 201"],
    build: ["Suchen Sie das Seminar?", "Are you looking for the seminar?", "Where is room two hundred ten?", "Wo ist Raum zweihundertzehn"],
    reply: ["Im zweiten Stock, rechts.", "On the second floor, on the right.", "Is there a lift?", "Gibt es einen Aufzug"],
    finish: ["Ja, neben der Treppe.", "Yes, next to the stairs.", "When does the seminar start?", "Wann beginnt das Seminar"],
  },
  {
    id: "exam", topic: "Study", title: "Before the exam", place: "At the examinations office",
    challenge: "Check an exam-registration deadline and required identification.",
    listen: ["Die Anmeldung endet am Montag um zwölf Uhr mittags.", "Registration ends on Monday at twelve noon.", "When is the deadline?", "Monday at noon", "Monday at midnight", "Tuesday at noon"],
    build: ["Sind Sie schon angemeldet?", "Are you already registered?", "How can I register for the exam?", "Wie kann ich mich für die Prüfung anmelden"],
    reply: ["Das geht über das Studierendenportal.", "You can do that through the student portal.", "Which documents do I need?", "Welche Unterlagen brauche ich"],
    finish: ["Bringen Sie zur Prüfung Ihren Ausweis mit.", "Bring your ID to the exam.", "Thank you for the information", "Danke für die Information"],
  },
  {
    id: "group-project", topic: "Study", title: "Plan a group project", place: "With your study group",
    challenge: "Agree on a meeting time and take responsibility for a task.",
    listen: ["Wir treffen uns am Mittwoch um drei in der Bibliothek, nicht online.", "We are meeting on Wednesday at three in the library, not online.", "Where is the meeting?", "In the library", "Online", "In the canteen"],
    build: ["Welchen Teil möchtest du übernehmen?", "Which part would you like to take on?", "I can prepare the introduction", "Ich kann die Einleitung vorbereiten"],
    reply: ["Schaffst du das bis Dienstag?", "Can you manage that by Tuesday?", "Yes, I will send it on Monday", "Ja, ich schicke es am Montag"],
    finish: ["Super, dann fehlt nur noch die Präsentation.", "Great, then only the presentation is missing.", "Shall we practise together?", "Sollen wir zusammen üben"],
  },
  {
    id: "professor", topic: "Study", title: "Ask your lecturer", place: "During office hours",
    challenge: "Ask a lecturer to clarify a task and its deadline.",
    listen: ["Die Hausarbeit muss bis zum fünfzehnten Juni als PDF eingereicht werden.", "The term paper must be submitted as a PDF by June fifteenth.", "Which format is required?", "PDF", "A printed poster", "An audio recording"],
    build: ["Wobei brauchen Sie Hilfe?", "What do you need help with?", "I have a question about the assignment", "Ich habe eine Frage zur Aufgabe"],
    reply: ["Was ist Ihnen unklar?", "What is unclear to you?", "Could you give an example?", "Könnten Sie ein Beispiel geben"],
    finish: ["Natürlich, wir schauen uns ein Beispiel an.", "Of course, we will look at an example.", "Now I understand it better", "Jetzt verstehe ich es besser"],
  },
  {
    id: "job-interview", topic: "Work", title: "Introduce your experience", place: "In a job interview",
    challenge: "Rehearse a short introduction and ask about working hours.",
    listen: ["Die Stelle umfasst zwanzig Stunden pro Woche. Der Arbeitsbeginn ist flexibel.", "The position is twenty hours per week. The starting time is flexible.", "How many hours per week?", "Twenty", "Thirty", "Forty"],
    build: ["Erzählen Sie etwas über sich.", "Tell us something about yourself.", "I am studying computer science", "Ich studiere Informatik"],
    reply: ["Haben Sie schon Berufserfahrung?", "Do you already have professional experience?", "I have completed an internship", "Ich habe ein Praktikum gemacht"],
    finish: ["Haben Sie noch Fragen an uns?", "Do you have any questions for us?", "What are the working hours?", "Wie sind die Arbeitszeiten"],
  },
  {
    id: "first-day", topic: "Work", title: "Your first day", place: "At a new workplace",
    challenge: "Introduce yourself and ask who to contact for help.",
    listen: ["Dein Arbeitsplatz ist im ersten Stock. Die Küche ist im Erdgeschoss.", "Your workstation is on the first floor. The kitchen is on the ground floor.", "Where is the kitchen?", "On the ground floor", "On the first floor", "In the basement"],
    build: ["Willkommen im Team!", "Welcome to the team!", "I am looking forward to working together", "Ich freue mich auf die Zusammenarbeit"],
    reply: ["Wir richten gleich deinen Zugang ein.", "We will set up your access shortly.", "Who can help me with questions?", "Wer kann mir bei Fragen helfen"],
    finish: ["Du kannst jederzeit zu mir kommen.", "You can come to me at any time.", "Thank you, that helps me a lot", "Danke, das hilft mir sehr"],
  },
  {
    id: "meeting", topic: "Work", title: "Speak in a meeting", place: "In a team meeting",
    challenge: "Ask for clarification and summarise your next action.",
    listen: ["Wir verschieben die Besprechung von Dienstag auf Donnerstag.", "We are moving the meeting from Tuesday to Thursday.", "What is the new meeting day?", "Thursday", "Tuesday", "Friday"],
    build: ["Sind alle mit dem Plan einverstanden?", "Does everyone agree with the plan?", "I have a suggestion", "Ich habe einen Vorschlag"],
    reply: ["Ja, bitte. Wir hören zu.", "Yes, please. We are listening.", "Could we test that first?", "Könnten wir das zuerst testen"],
    finish: ["Gute Idee. Kannst du den Test vorbereiten?", "Good idea. Can you prepare the test?", "I will prepare it by Thursday", "Ich bereite ihn bis Donnerstag vor"],
  },
  {
    id: "sick-leave", topic: "Work", title: "Call in sick", place: "Calling your workplace",
    challenge: "Practise notifying your workplace and asking about its reporting procedure.",
    listen: ["Bitte informieren Sie auch Ihre Teamleitung und prüfen Sie unsere Krankmelderegeln.", "Please also inform your team lead and check our sickness-reporting rules.", "Who else should be informed?", "Your team lead", "Your landlord", "The library"],
    build: ["Guten Morgen, was ist los?", "Good morning, what is wrong?", "I am ill and cannot come today", "Ich bin krank und kann heute nicht kommen"],
    reply: ["Gute Besserung. Melden Sie sich morgen bitte noch einmal.", "Get well soon. Please contact us again tomorrow.", "I will let you know tomorrow", "Ich gebe Ihnen morgen Bescheid"],
    finish: ["Haben Sie noch Fragen?", "Do you have any more questions?", "Do I need a certificate?", "Brauche ich eine Bescheinigung"],
  },
  {
    id: "feedback", topic: "Work", title: "Ask for feedback", place: "After a presentation",
    challenge: "Ask for specific feedback and agree on an improvement.",
    listen: ["Die Beispiele waren gut. Die Zusammenfassung könnte kürzer sein.", "The examples were good. The summary could be shorter.", "What should be shorter?", "The summary", "The examples", "The meeting invitation"],
    build: ["Wie fandest du die Präsentation?", "What did you think of the presentation?", "I would like some feedback", "Ich hätte gern Feedback"],
    reply: ["Die Zusammenfassung war etwas lang.", "The summary was a little long.", "What could I improve?", "Was könnte ich verbessern"],
    finish: ["Konzentriere dich auf drei wichtige Punkte.", "Focus on three important points.", "I will try that next time", "Das probiere ich nächstes Mal"],
  },
  {
    id: "bus", topic: "Travel", title: "Take the right bus", place: "At a bus stop",
    challenge: "Check a route and ask where to get off.",
    listen: ["Die Linie zwölf fährt zum Krankenhaus. Zum Rathaus nehmen Sie die Linie sechs.", "Route twelve goes to the hospital. For the town hall, take route six.", "Which bus goes to the town hall?", "Route six", "Route twelve", "Route twenty"],
    build: ["Wohin möchten Sie?", "Where would you like to go?", "Does this bus go to the town hall?", "Fährt dieser Bus zum Rathaus"],
    reply: ["Ja, steigen Sie bitte ein.", "Yes, please get on.", "Where must I get off?", "Wo muss ich aussteigen"],
    finish: ["An der dritten Haltestelle.", "At the third stop.", "Could you let me know?", "Könnten Sie mir Bescheid sagen"],
  },
  {
    id: "hotel", topic: "Travel", title: "Check in smoothly", place: "At a hotel",
    challenge: "Check in and ask about breakfast and checkout.",
    listen: ["Frühstück gibt es von sieben bis zehn. Auschecken müssen Sie bis elf Uhr.", "Breakfast is from seven to ten. You must check out by eleven.", "When is checkout due?", "By 11:00", "By 7:00", "By 10:00"],
    build: ["Haben Sie reserviert?", "Have you made a reservation?", "I have a reservation under Weber", "Ich habe eine Reservierung auf den Namen Weber"],
    reply: ["Hier ist Ihre Zimmerkarte.", "Here is your room card.", "Is breakfast included?", "Ist das Frühstück inbegriffen"],
    finish: ["Ja, im Restaurant im Erdgeschoss.", "Yes, in the restaurant on the ground floor.", "Where is the lift?", "Wo ist der Aufzug"],
  },
  {
    id: "directions", topic: "Travel", title: "Find your way", place: "In the city centre",
    challenge: "Ask for directions and repeat the key step to confirm it.",
    listen: ["Gehen Sie geradeaus und an der zweiten Ampel nach links.", "Go straight ahead and turn left at the second traffic light.", "Where should you turn left?", "At the second traffic light", "At the first corner", "After the bridge"],
    build: ["Kann ich Ihnen helfen?", "Can I help you?", "How do I get to the museum?", "Wie komme ich zum Museum"],
    reply: ["Zu Fuß sind es etwa zehn Minuten.", "It is about ten minutes on foot.", "Is it far from here?", "Ist es weit von hier"],
    finish: ["Nein, immer geradeaus, dann links.", "No, straight ahead, then left.", "So straight ahead and then left?", "Also geradeaus und dann links"],
  },
  {
    id: "ticket", topic: "Travel", title: "Choose a ticket", place: "At the ticket desk",
    challenge: "Ask about ticket validity before buying.",
    listen: ["Die Tageskarte gilt bis drei Uhr am nächsten Morgen, aber nur in Zone A.", "The day ticket is valid until three the next morning, but only in zone A.", "Where is the ticket valid?", "Only in zone A", "In all zones", "Only on trains to Berlin"],
    build: ["Welche Fahrkarte möchten Sie?", "Which ticket would you like?", "I would like a day ticket", "Ich hätte gern eine Tageskarte"],
    reply: ["Für welche Zone?", "For which zone?", "Which zone do I need for the airport?", "Welche Zone brauche ich für den Flughafen"],
    finish: ["Dafür brauchen Sie die Zone B.", "For that you need zone B.", "Then one ticket for zone B, please", "Dann eine Fahrkarte für Zone B, bitte"],
  },
  {
    id: "cycling", topic: "Travel", title: "Repair your bicycle", place: "At a bicycle workshop",
    challenge: "Describe a bicycle fault and ask for a repair estimate.",
    listen: ["Wir können den Reifen heute reparieren. Die Bremsen prüfen wir morgen.", "We can repair the tyre today. We will check the brakes tomorrow.", "What can be repaired today?", "The tyre", "The brakes", "The lights"],
    build: ["Was stimmt mit dem Fahrrad nicht?", "What is wrong with the bicycle?", "The rear tyre is flat", "Der Hinterreifen ist platt"],
    reply: ["Wir schauen uns das an.", "We will take a look.", "How much will the repair cost?", "Wie viel kostet die Reparatur"],
    finish: ["Ungefähr fünfundzwanzig Euro.", "About twenty-five euros.", "When can I collect the bicycle?", "Wann kann ich das Fahrrad abholen"],
  },
  {
    id: "invitation", topic: "Social", title: "Make weekend plans", place: "Talking with a friend",
    challenge: "Accept an invitation and suggest a meeting point.",
    listen: ["Am Samstag regnet es. Lass uns lieber am Sonntag spazieren gehen.", "It will rain on Saturday. Let's go for a walk on Sunday instead.", "Which day is suggested for the walk?", "Sunday", "Saturday", "Friday"],
    build: ["Hast du am Sonntag Zeit?", "Do you have time on Sunday?", "Yes, that sounds good", "Ja, das klingt gut"],
    reply: ["Wo wollen wir uns treffen?", "Where shall we meet?", "Shall we meet at the station?", "Sollen wir uns am Bahnhof treffen"],
    finish: ["Gern, um zehn?", "Gladly, at ten?", "Perfect, see you on Sunday", "Perfekt, bis Sonntag"],
  },
  {
    id: "gym", topic: "Social", title: "Try a new class", place: "At a sports centre",
    challenge: "Ask about a trial class and what you need to bring.",
    listen: ["Der Anfängerkurs ist dienstags um achtzehn Uhr. Die erste Stunde ist kostenlos.", "The beginners' class is on Tuesdays at eighteen hundred. The first session is free.", "Which session is free?", "The first session", "Every Tuesday session", "The final session"],
    build: ["Möchten Sie einen Kurs buchen?", "Would you like to book a class?", "Can I try a session first?", "Kann ich zuerst eine Stunde ausprobieren"],
    reply: ["Ja, kommen Sie am Dienstag vorbei.", "Yes, come by on Tuesday.", "Do I need to register?", "Muss ich mich anmelden"],
    finish: ["Ja, bitte über unsere Webseite.", "Yes, please use our website.", "What should I bring?", "Was soll ich mitbringen"],
  },
  {
    id: "bakery", topic: "Food", title: "Breakfast to go", place: "At the bakery",
    challenge: "Buy breakfast and ask about an ingredient in German.",
    listen: ["Die Vollkornbrötchen sind noch warm. Drei Stück kosten zwei Euro.", "The wholegrain rolls are still warm. Three cost two euros.", "What costs two euros?", "Three wholegrain rolls", "Two wholegrain rolls", "Three coffees"],
    build: ["Wie viele möchten Sie?", "How many would you like?", "I would like three rolls, please", "Ich hätte gern drei Brötchen, bitte"],
    reply: ["Möchten Sie noch ein Stück Kuchen?", "Would you also like a piece of cake?", "Does the cake contain nuts?", "Sind Nüsse im Kuchen"],
    finish: ["Ja, der Kuchen enthält Haselnüsse.", "Yes, the cake contains hazelnuts.", "Then just the rolls, please", "Dann nur die Brötchen, bitte"],
  },
  {
    id: "restaurant", topic: "Food", title: "A table for two", place: "At the restaurant",
    challenge: "Ask for a table and order a drink without switching languages.",
    listen: ["Drinnen ist alles besetzt, aber draußen ist noch ein Tisch frei.", "Everything inside is occupied, but a table outside is available.", "Where is a table available?", "Outside", "Inside by the window", "Only at the bar"],
    build: ["Möchten Sie draußen sitzen?", "Would you like to sit outside?", "Yes, a table for two, please", "Ja, einen Tisch für zwei, bitte"],
    reply: ["Was möchten Sie trinken?", "What would you like to drink?", "I would like still water", "Ich hätte gern stilles Wasser"],
    finish: ["Hier ist Ihr Wasser.", "Here is your water.", "Could we have the menu, please?", "Könnten wir bitte die Speisekarte haben"],
  },
];

export const EXTRA_CHAPTERS: Mission[] = chapters.map((chapter, index) => {
  const [line, translation, task, answer, alternative, other] = chapter.listen;
  return {
    id: chapter.id, topic: chapter.topic, title: chapter.title,
    subtitle: chapter.challenge, challenge: chapter.challenge, place: chapter.place,
    image: chapter.topic === "Food" ? "/images/cafe.jpg" : chapter.topic === "Travel" ? "/images/station.jpg" : chapter.topic === "Health" ? "/images/appointment.jpg" : "/images/neighbors.jpg",
    partner: "Mila", role: "Conversation partner", skill: "production", minutes: 6,
    turns: [
      { kind: "listen", line, translation, task, options: index % 3 === 0 ? [answer, other, alternative] : index % 3 === 1 ? [alternative, answer, other] : [other, alternative, answer], accepted: [answer], note: translation },
      response("build", chapter.build), response("respond", chapter.reply), response("respond", chapter.finish),
    ],
  };
});